### ISSUE TITLE
Visualization part

### ISSUE THREAD

**Issue by xiaoiker** [himashi92/VT-UNet#1]
Hi,

Great work and thanks for sharing the code. Could ask how did you visualize the result? Could you share the scripts?

Best,
Wei

**Comment by himashi92** [comment]
Hi Wei,

Once you trained the model, you can use test.py script to generate predictions and these predictions will be saved as MRI volumes. You can use MRI/CT viewing application to view those predictions. For example, I use Mango Software: https://en.wikipedia.org/wiki/Mango_(software) . There is an option to get snapshots of the slices that you want to save as images.

Best Regards,
Himashi
