### ISSUE TITLE
How to draw this chart？

### ISSUE THREAD

**Issue by YuchaoLau** [himashi92/VT-UNet#14]
Hello, your work is very interesting. I want to know how to draw this kind of chart. Thank you very much！
![image](https://user-images.githubusercontent.com/54919837/166088733-482c55fb-e3e6-41cd-88e3-f3c617266fa5.png)

**Comment by himashi92** [comment]
Hi, I used an excel sheet to generate this chart. I attached my working excel here.

[teaser.xlsx](https://github.com/himashi92/VT-UNet/files/8596822/teaser.xlsx)

**Comment by YuchaoLau** [comment]
Thank you for your reply in your busy time. This solved my problem.
