### ISSUE TITLE
Ask for data help

### ISSUE THREAD

**Issue by huying12** [himashi92/VT-UNet#15]
Hello, I'd like to ask if you can provide the treatment of liver or pancreatic tumors. The code shows the treatment of brats2021 data. I need to deal with the segmentation of gastric cancer data. The data type is DCM. Thank you for sharing.

**Comment by huying12** [comment]
Thank you for your reply. My data set is in the file. The format of the original data set is DCM, and the original case is named (chonsen DICOM) commom as jstcm 01 pingsao; The seg dataset is named nrrd_ DCM, which contains the segmentation corresponding to each case slice. After that, I convert DCM to NII format and save the original case and segmented data set in nii folder respectively. Because there is T1 \ t1ce \ T2 \ flair file in MRI, I copied the original case NII into four copies and named them in turn. It was found that the result diagram could not appear in the code and could not be used after many adjustments. I would appreciate your help.




胡颖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "himashi92/VT-UNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月25日(星期三) 上午9:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [himashi92/VT-UNet] Ask for data help (Issue #15)





 
Hello, we'll release our updated code soon. Meanwhile, can you send me more details about your dataset? So that I can send some preprocessing scripts that might be useful for your work. Once you preprocess your data, you can use the VT-UNet code base.
 
Thanks,
 Himashi
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

(chonsen dicom) Commom AS JSTCM 01 pingsao.zip (177.90M, 2022年06月24日 09:35 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=52396263e0f8d5c1a67a40fa4763061a055f5550545404011c0c5055584e0006080c4f5a03510518065b035652525606535a5453614d341d52510d0d12065a155550010c0c4a14765e540f0c0c43756611733137222e14050019120a0f0447545e17180a116309&code=19bcac45




nii.zip (212.74M, 2022年06月24日 09:36 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0d656365527bd193a62641fc4763574e095c5354005550501c5c0106504e5105535c4e5d0402014c5453565c58020355005756526164650f580c4d1f0813655c&code=1eceacea

**Comment by himashi92** [comment]
Hi huying, as per my understanding, it seems your dataset has one nii file as input, unlike BraTS dataset. You do not need to have T1/T1CE/T2/FLARE files to do your task. Instead, get the preprocessed nii file and modify the input channel number as 1 instead of 4. 

If you are still unable to run the code, send me an email with error screenshots. I'll try to help you.

Thanks,
Himashi

**Comment by huying12** [comment]
Thank you for your reply.！There was an error in the training folder picture. At the beginning, I changed the input channel from 4 to 1. The training can be carried out normally. However, during the test, there was a mismatch with the pre training model. The training folder picture was an error. I don't know how to change it.&nbsp;


At the same time, I changed the pre training model to the mode generated during training_ Best PTH, but the result is wrong. In document 02 NII is the generated result.


I have several questions. First, do I need to adjust the DCM size to the same size as MRI? How can i get the preprocessed nii file? Secondly, the number of MRI tags you handle is 3, while mine is only one and unnamed. I would like to know how you handle it when running MSD pancreas data? (did you use the new code or did you change the operation on the original brats code?)


Sorry to disturb you. I look forward to your reply!





胡颖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "himashi92/VT-UNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 下午2:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [himashi92/VT-UNet] Ask for data help (Issue #15)





 
Hi huying, as per my understanding, it seems your dataset has one nii file as input, unlike BraTS dataset. You do not need to have T1/T1CE/T2/FLARE files to do your task. Instead, get the preprocessed nii file and modify the input channel number as 1 instead of 4.
 
If you are still unable to run the code, send me an email with error screenshots. I'll try to help you.
 
Thanks,
 Himashi

**Comment by himashi92** [comment]
Hi huying, Can you tell me what is the resolution size of your nii? The Pancreas CT dataset I trained was initially 512x512x**. So I had to downsample the input during preprocessing before I feed those nii files to the model. All these scripts will be released soon.

VT-unet input should be 128x128x128 and in your case, the task is binary segmentation where you have only two classes (0-background, 1-class). In order to train and evaluate (test), scripts need some modifications like changing input channel =1 and output channel =1.

Regards,
Himashi

**Comment by huying12** [comment]
Hi,Himashi.My CT data resolution is 512*512*xx. I found that the data processing part of the code can finally change the image resolution to 128*128*128, or do I need to preprocess the image again before input?


When you test MSD pancreas data, the pre training model used is the mode_ best_ base. pth that previously downloaded from the Internet, or the mode_ best.pth that&nbsp; generated during the train ? Because I found that after I changed the I / O channel to 1, I used the downloaded model_ best_ base. pth, the pre training model does not match the network structure. How do you handle it?


I'm still preparing for my final exam. I'm sorry to disturb you recently. I wish you a happy life.



Regards,
Huying


胡颖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "himashi92/VT-UNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 上午8:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [himashi92/VT-UNet] Ask for data help (Issue #15)





 
Hi huying, Can you tell me what is the resolution size of your nii? The Pancreas CT dataset I trained was initially 512x512x**. So I had to downsample the input during preprocessing before I feed those nii files to the model. All these scripts will be released soon.
 
VT-unet input should be 128x128x128 and in your case, the task is binary segmentation where you have only two classes (0-background, 1-class). In order to train and evaluate (test), scripts need some modifications like changing input channel =1 and output channel =1.
 
Regards,
 Himashi

**Comment by himashi92** [comment]
Hi Huying,

You need to use the model that is generated during your training. The given model_best_base.pth is for BraTS dataset and that will not work for your model.

Best Regards,
Himashi
