### ISSUE TITLE
Question about init_weights function in SwinTransformerSys3D class

### ISSUE THREAD

**Issue by TanThinNguyen** [himashi92/VT-UNet#16]
Hi @himashi92,
First of all, thank you very much for your great project.
I have a question about the `init_weights` function in class `SwinTransformerSys3D` 
https://github.com/himashi92/VT-UNet/blob/2c5c5451a8e61d0884d5ddc3b487494602fd6e37/vtunet/vt_unet.py#L1076

I am reading the code of this class and I see the `init_weights` function seems not to be used anywhere when creating model for training or testing in `train.py` or `test.py` files. 

I hope you will answer my question. Thank you.
Tan Thin Nguyen.

**Comment by himashi92** [comment]
Hi @TanThinNguyen, those two functions were not used, and instead, I used the following function to load pre-trained weights of imagenet.

https://github.com/himashi92/VT-UNet/blob/2c5c5451a8e61d0884d5ddc3b487494602fd6e37/vtunet/vision_transformer.py#L52

Thanks & Regards,
Himashi
