### ISSUE TITLE
Training with liver and pancreas datasets

### ISSUE THREAD

**Issue by BelieferQAQ** [himashi92/VT-UNet#20]
Hello, I want to use the liver and pancreas datasets for training. Which part of the code should I change

**Comment by himashi92** [comment]
Hello, I released the newest version of the code. Now you can use nnUNet configurations to test vt-unet's performance on other datasets.

**Comment by BelieferQAQ** [comment]
> 

RibFrac dataset，ok？

**Comment by himashi92** [comment]
Please follow the steps given in nnUNet code: https://github.com/MIC-DKFZ/nnUNet#how-to-run-nnu-net-on-a-new-dataset

**Comment by BelieferQAQ** [comment]
> Please follow the steps given in nnUNet code: https://github.com/MIC-DKFZ/nnUNet#how-to-run-nnu-net-on-a-new-dataset

ok，thank you
