### ISSUE TITLE
Issue with training

### ISSUE THREAD

**Issue by Chadkowski** [himashi92/VT-UNet#23]
Hi! I am trying to train the vtunet but the process is not starting i nthe background with nohup. Any idea why?

**Comment by himashi92** [comment]
Hi! Did you try with sudo?

**Comment by Chadkowski** [comment]
Hi! yes, I think the directory is hardcoded in one file so I think that might be causing the issue. I'll try running everything from /home/ and let you know how it goes.

**Comment by Chadkowski** [comment]
solved: change the env variables in etc/environment instead of ~./profile bashrc as stated in the readme.

**Comment by Chadkowski** [comment]
question now remains how to configure for training? Whenever I run it I think I'm overflowing my GPU.. any ideas?

**Comment by himashi92** [comment]
Hi, can you reduce the batch size and run it again? Modify batch size in this file: https://github.com/himashi92/VT-UNet/blob/main/VTUNet/vtunet/run/default_configuration.py

**Comment by Chadkowski** [comment]
> Hi, can you reduce the batch size and run it again? Modify batch size in this file: https://github.com/himashi92/VT-UNet/blob/main/VTUNet/vtunet/run/default_configuration.py

should be ok now if I reduce to "batch-size=1". 

Thanks!

**Comment by Chadkowski** [comment]
Question, the pre-determiend "Synapse"-parameters in the default_configuration.py ----- Are these defined for the "synapse multi-organ segmentation dataset"??

@himashi92

**Comment by himashi92** [comment]
yes, the code was adapted from nnUNet and nnFormer.  We haven't trained VT-UNet on those datasets yet. But you can try those configurations to train VT-UNet on Synapse Multi Organ dataset.
