### ISSUE TITLE
Version2

### ISSUE THREAD

**Issue by procyontao** [himashi92/VT-UNet#24]
Hi,

Nice work. Previously you said in README that this new version will perform better than version1. Could you briefly explain whether and what you have changed in the network structure to make it better?

Thank you.

**Comment by himashi92** [comment]
Hi,

Thank you for your interest in this work. Structural perspective there are no differences at all (But you can change VT-UNet configurations in YAML files for small and base versions). Network training perspective, using nnUNet configurations, we now train VT-UNet with data pre-processing and data augmentations (we didn't use any augmentation techniques in our version 1).  

Best Regards,
Himashi
