### ISSUE TITLE
About Results on BraTS

### ISSUE THREAD

**Issue by auroua** [himashi92/VT-UNet#26]
The paper <A Volumetric Transformer for Accurate 3D Tumor Segmentation> evaluates the VT-UNet's performance on BraTS 2021 dataset, but the MICCAI paper <A Robust Volumetric Transformer for Accurate 3D Tumor Segmentation> evaluates the VT-UNet on MSD BraTS task. Why not evaluate and report the performance of VT-UNet on BraTS 2021 any more in the MICCAI paper?

**Comment by himashi92** [comment]
For a fair comparison with other methods, we used results on MSD BraTS dataset in our MICCAI paper instead of BraTS 2021 dataset. In the future, we'll be considering extending our experiments on other datasets as well (possibly in a journal extension of the MICCAI work).

**Comment by auroua** [comment]
@himashi92 Thanks for your reply!
