### ISSUE TITLE
task 4 issue

### ISSUE THREAD

**Issue by b3r-prog** [himashi92/VT-UNet#30]
For the hippocampus task, I am getting this error: 

`    x = x.view(B, D * 8, H, W, C)
RuntimeError: shape '[9, 32, 4, 4, 1152]' is invalid for input of size 414720`. I set the number of channels to 1 and preprocessed the data. Any suggestions on how to resolve this?

**Comment by himashi92** [comment]
what is the input size of your scan? It should be 128x128x128. At the moment, VT-UNet can only process an input size of 128x128x128.
