### ISSUE TITLE
Training & Testing On MSD Data

### ISSUE THREAD

**Issue by abdur75648** [himashi92/VT-UNet#5]
First of all, thanks @himashi92 for this amazing work.
Since we do not have access to BraTS data and want to run your model on the MSD data set given [ here](https://drive.google.com/drive/folders/1HqEgzS8BV2c7xYNrZdEAnrHk7osJJ--2), it would be very helpful if you could help me with that.
What will be the tree structure of the code before running & what changes in the code need to be done?
It would be further more helpful if could add your code of running it on MSD data here in this repo.

**Comment by himashi92** [comment]
Hi Abdur,

You can follow the same code as in Brats.py script to formulate MSD dataset script. You have to modify the code for two classes Tumor and Organ(Pancreas/Liver).

Training and Testing the model is similar to what I have provided in the repo for BraTS dataset.

Thanks & Regards,
Himashi

**Comment by JTTurnerDeloitte** [comment]
Thank you @himashi92 for this work! I'm encountering a problem when trying to replicate the BRATS brain with the pancreas

The `dataset.pancreas` file that I created inserts patients into the data array as such:

`{'id': 'pancreas_001.nii.gz',
 'im': 'data/MSD/Task07_Pancreas/imagesTr/pancreas_001.nii.gz',
 'seg': 'data/MSD/Task07_Pancreas/labelsTr/pancreas_001.nii.gz'}`

where `data` is the appropriate symlink and I get the following error:

`RuntimeError: Given groups=1, weight of size [96, 4, 4, 4, 4], expected input[1, 1, 128, 128, 128] to have 4 channels, but got 1 channels instead`

thrown by line:

`VT-UNet/vtunet/vt_unet.py", line 772, in forward
    x = self.proj(x)  # B C D Wh Ww`

The `96` is different based on the config I am using. Any ideas what other changes to make?

**Comment by himashi92** [comment]
Hi JT,

For Brats task we have 4 modalities of MRI, therefore input channel size is 4. But for Pancreas dataset we have only 1 modality, therefore input channel size is 1. https://github.com/himashi92/VT-UNet/blob/00f3b422891d240f437adafa24e7fd8225796252/vtunet/vision_transformer.py#L29 change in_chans=1 here.

Thanks, 
Himashi

**Comment by BelieferQAQ** [comment]
> 

Excuse me, when training CT data, what changes should be made to the program

**Comment by BelieferQAQ** [comment]
> 

How to set the output channel? For example, if there are five types of ribs, should the output channel be set to 6, plus the background，thank you

**Comment by JTTurnerDeloitte** [comment]
That is correct. 0 is background, 1-N is any number of N objects you are segmenting.
