### ISSUE TITLE
Data processing questions about Brats21

### ISSUE THREAD

**Issue by 834799106** [himashi92/VT-UNet#6]
Thank you very much for your excellent work, I noticed that in your Brats.py code, the fusion of different tags into ET, TC, WT also occurs in many data processing examples, such as Monai. But I see that your paper is still classified and evaluated according to the label of the competition, right?
  Looking forward to your reply.

**Comment by himashi92** [comment]
Yes, class labeling and evaluation are similar to the competition.

**Comment by 834799106** [comment]
Hi, Later, I continued to try your method on Brats21, using 2D Swin-T pre-trained weights and the initialization parameter model for training respectively (Training is not finished now). The pre-training model did play a good convergence effect, but the initialization model made me feel some fluctuations. Is this a normal phenomenon?
<img width="213" alt="1642834602(1)" src="https://user-images.githubusercontent.com/78247190/150628486-485cbf6a-0c99-4715-9180-292daa1d4b59.png">
